#! /usr/bin/env python
"""
Usage:
  run_folder_actions (-d DEFAULT_ACTION | --default DEFAULT_ACTION)
  run_folder_actions [-d DEFAULT_ACTION | --default DEFAULT_ACTION] (ACTION)...
  
Arguments:
  ACTION  an action specifier in the format of glob=path and, yes, this needs to be quoted appropriately
  DEFAULT_ACTION  same as ACTION

Options:
  -h --help     Show this screen.

"""
from docopt import docopt


if __name__ == '__main__':
    arguments = docopt(__doc__, version='Folder Actions v 0.0.1')
    print(arguments)
