#! /usr/bin/env bash
pushd difftest/data >> /dev/null 2>&1
../../run_folder_actions -f ../handlers/on_failure -s ../handlers/on_success -a "*.gif=../actions/run_me_for_gifs" -e ../handlers/after_each
